defaultheaders:
  User-Agent: "SentinelGo Client v1.0"
  Accept-Language: "en-US,en;q=0.9"
customcookies:
  - name: "session_id"
    value: "dummycookie123"
    path: "/"
    domain: "example.com"
maxretries: 3
riskthreshold: 80.5
apikeys:
  virustotal: "YOUR_VT_API_KEY"
